import localFont from "next/font/local";
import globalStyle  from "./globals.module.css";
import {ThemeProvider} from "@mui/material";
import {theme} from "@/theme";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
      <link href="https://fonts.googleapis.com/css2?family=Montez&display=swap" rel="stylesheet"/>
      <title>WD Theme Starer</title>
    </head>
    <ThemeProvider theme={theme}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {children}
      </body>
    </ThemeProvider>
    </html>
  );
}
